name: Wikipedia - Fetch `Current events` content
on:
  workflow_dispatch:
  schedule:
    - cron: '09,39 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests bleach

      - name: Run fetch script
        run: python .github/workflows/fetch_current_events.py
                
      - name: Update content file and version
        if: env.CHANGE == 'true'
        shell: bash
        run: |
          echo "updating content file"
          echo -n "$CONTENT" > 'content.js'
          echo "updating content version"
          sed -i 's/content.js?v=[0-9]*/content\.js\?v='"$(date '+%Y%m%d%H%M%S')"'/g' index.html
            
      - name: Commit & Push
        if: env.CHANGE == 'true'
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'update file content'
