name: Wikipedia - Get `Current events` content
on:
  workflow_dispatch:
  schedule:
#   - cron: '39 * * * *'
    - cron: '09,39 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests bleach

      - name: Run script
        shell: python
        run: |
          import os, re, requests, bleach
          def remove_pictured(r):
            pos = r.find('pictured')
            if pos < 0: return r
            l = len(r)
            while pos < l:
                if r[pos] == ')':
                    break
                pos += 1
            if pos >= l: return r
            end = pos
            close = 0
            start = -1
            while pos >= 0:
                if r[pos] == ')':
                    close += 1
                elif r[pos] == '(':
                    close -= 1
                if close == 0:
                    start = pos
                    break
                pos -= 1
            if start >= 0 and end >= 0:
                return (r[0:max(start, 0)] + r[1+end:]).replace(' <i></i>', '').replace('<i></i>', '').replace('  ', ' ').replace(' .', '.').replace(' ,', ',')
            return r
          r = requests.get('https://en.wikipedia.org/wiki/Portal:Current_events').text
          r = r.split('id="Topics_in_the_news"', 1)[1].split('<ul>', 1)[1].split('</ul>', 1)[0]
          r = ' '.join(r.splitlines())
          ab = bleach.clean(r, attributes = {'a': ['href', 'title']}, strip=True)
          
          if ab != r:
            print('content change after bleach!')
            print('before:')
            print(r)
            print('after:')
            print(ab)
          
          r = '<ol>' + ab + '</ol>'
          r = r.replace("'", r"\'")
          ar = remove_pictured(r)
          
          if ar != r:
            print('content change after removing picture text:')
            print('before:')
            print(r)
            print('after:')
            print(ar)          
          
          r = "const content = '" + ar + "';"
          
          env_file = os.getenv('GITHUB_ENV')

          with open('content.js') as f: 
            s = f.read().strip()
            print('current file content:')
            print(s)
            print('fetched content:')
            print(r)
            if s == r:
              print('no content change')
              with open(env_file, 'a') as f:
                f.write("CHANGE=false\n")
            else:
              print('content change')
              with open(env_file, 'a') as f:
                f.write("CHANGE=true\nCONTENT=" + r)
                
      - name: Update content file and version
        if: env.CHANGE == 'true'
        shell: bash
        run: |
          echo "updating content file"
          echo -n "$CONTENT" > 'content.js'
          echo "updating content version"
          sed -i 's/content.js?v=[0-9]*/content\.js\?v='"$(date '+%Y%m%d%H%M%S')"'/g' index.html
            
      - name: Commit & Push
        if: env.CHANGE == 'true'
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'update file content'
